### ISSUE TITLE
warning of fps_max appearing when it shouldn't

### ISSUE THREAD

**Issue by Vykori** [p2sr/Portal2SpeedrunMod#10]
in my autoexec I set fps_max to 140, but on loading screens I'm getting a warning in the top right corner "fps_max is at a banned value" so I verified but the cvar is definitely still set to 140 currently

<img width="224" alt="2022-09-12 11_02_22-Portal 2 Speedrun Mod - Direct3D 9" src="https://user-images.githubusercontent.com/16940637/189727823-72c1a116-260f-43dc-8de2-f91b80950ab4.png">

**Comment by ThisAMJ** [comment]
This is likely due to `sar_fast_load_preset` unsetting `fps_max` during loads. Don't worry, your runs are still valid. (provided there's no other cheatiness going on)

**Comment by betsruner** [comment]
Issue seems resolved
