### ISSUE TITLE
turret sabotage door speed

### ISSUE THREAD

**Issue by ThisAMJ** [p2sr/Portal2SpeedrunMod#21]
https://clips.twitch.tv/TrustworthyBashfulRutabagaPermaSmug-Cmqxsb5UnOj18Ffr

**Comment by betsruner** [comment]
Completed on personal repo will merge later when rest is done
https://github.com/Alex-Marek/Portal2SpeedrunMod/commit/c027c4ea7a60944d55cccb524e35dabebc473053
