### ISSUE TITLE
[Linux] Scuffed camera 

### ISSUE THREAD

**Issue by DarkblooM-IO** [p2sr/Portal2SpeedrunMod#3]
As of the latest release, the camera flickers in a random direction whenever you move your mouse, making it very difficult to navigate or aim properly.

I have no idea where that might come from.

Don't know if it's the case on Windows as well.

I'm really not sure which info I should give so please feel free to ask for more details and I'll try my best to answer.

**Comment by mlugg** [comment]
This isn't related to the new Speedrun Mod release - instead, it's a recent regression in the game, specifically SDL. I believe it was caused by a bad update to the Steam Runtime libraries.
As a workaround for now you can disable raw input, either in the menu or with `m_rawinput 0`.

**Comment by facespkz** [comment]
I had this issue a while ago, and I fixed it by pointing LD_PRELOAD to an older version of 32-bit SDL (specifically 2.0.20). Installing older packages can break things, so you'll have to find the package for your distro and extract it elsewhere. The file you're looking for should be named `libSDL2-2.0.so.0.18.2`.
