### ISSUE TITLE
Unable to enter into the game

### ISSUE THREAD

**Issue by LikeToCodeStreams** [p2sr/Portal2SpeedrunMod#6]
keep on getting a unable to load manifest file error for the sound manifest file

**Comment by uncreativeCultist** [comment]
![image](https://user-images.githubusercontent.com/66176496/183998015-fe01ae62-2169-4634-adad-aad5ff858429.png)
same here.

**Comment by lucassimon963** [comment]
To fix this issue make sure that portal 2 from steam is installed on the same drive as the sourcemod folder.
So for example my portal 2 game is installed on my C: drive and I have the mod in my sourcefolder also on my C: drive.

**Comment by MrHousehao** [comment]
Hey, I have another solution. My steam and the game installation library are not on the same drive. The steam store program is D:\steam\steamapps\, and the game library is "G:\steam\steamapps\". If I directory put the mod under the "G :\steam\steamapps\sourcemods\", steam can't correctly recognize the mod. Only put it under the "D:\steam\steamapps\sourcemods\" can steam correctly recognize the mod. However, an error such as "unable to load manifest file error for the sound manifest file" may occur.
My solution is as follows:
1. First close steam and its accompanying programs such as OBS and wallpaper engine.
2. Move the "common" and "sourcemods" folders under the "D:\steam\steamapps\" directory of the steam store program to the "G:\steam\steamapps\" directory of the game library.
3. Open CMD (administrator mode) and use mklink command(Pay attention to the space character):
mklink /j "D:\steam\steamapps\common" "G:\steam\steamapps\common"
mklink /j "D:\steam\steamapps\sourcemods" "D:\steam\steamapps\sourcemods"
This command will cause the system to establish a folder mapping. Although there is the same file path in drive D, the file is actually stored in drive G, which does not affect steam's reading of the file from drive D.
I hope this can help people who have the same problems as me.

**Comment by ghost** [comment]
it is still coming up with the error message.

**Comment by ThisAMJ** [comment]
MrHousehao's solution is weird AF and not at all necessary. The proper fix is to edit `Portal 2 Speedrun Mod/gameinfo.txt`. Replace this line:
```
Game "|gameinfo_path|../../common/Portal 2/portal2"
```
with the correct path to the base game. e.g:
```
Game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2"
```

**Comment by ghost** [comment]
do i have to have the mod installed on the same drive as portal 2 or where steam i installed

**Comment by ThisAMJ** [comment]
no

**Comment by MrHousehao** [comment]
Yes, [ThisAMJ](https://github.com/ThisAMJ) solution was better and simpler than mine, and I use his solution now. thx

**Comment by ghost** [comment]
could this problem be caused by family sharing. 

dont ask

**Comment by ThisAMJ** [comment]
No. So long as the base game is installed and the `gameinfo.txt` in Speedrun Mod points to `<base game path>/portal2` as shown above, this error should not occur.

**Comment by broprogaming** [comment]
I Dont Know Why, But It Is Still Showing The Error For Me After Trying What ThisAMJ Said
![2022-12-06](https://user-images.githubusercontent.com/104804313/206048443-d81f8bbd-7610-4c12-bc73-5fb4ae40b485.png)
![2022-12-06 (3)](https://user-images.githubusercontent.com/104804313/206048636-dfdd17c9-06a2-46d5-b9ee-f2c533af53a2.png)

**Comment by ThisAMJ** [comment]
`C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2` *is* where the base game is installed right? You may also have to open the base game once before opening Speedrun Mod.

**Comment by broprogaming** [comment]
Yes, ill try to do that later, then tell you if that works or not

**Comment by broprogaming** [comment]
it doesnt work

**Comment by ThisAMJ** [comment]
Go here:
![Open Portal 2 path from steam (right click -> manage -> browse local files)](https://user-images.githubusercontent.com/69196954/206606019-879ae79e-bb39-400e-9f9c-e84d959aed68.png)
Then go into the `portal2` folder and click the search bar like this, then Ctrl+C:
![Click the file path at the top of File Explorer](https://user-images.githubusercontent.com/69196954/206607184-a93ad482-79ba-4fa8-a8b8-d5d49fd1fb54.png)
Then paste into `sourcemods/Portal 2 Speedrun Mod/gameinfo.txt`, inside quotes e.g:
```
Game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2"
```
If it still doesn't work, try verifying game files for the base game and reinstalling Speedrun Mod.

Make sure you only have one copy of Speedrun Mod installed, and check other drives as this issue only occurs when Portal 2 and Speedrun Mod are installed on separate drives.

If the problem persists, you will get assistance much quicker by asking in the #technical-help channel of the [P2SR discord server](https://discord.gg/p2sr).

**Comment by broprogaming** [comment]
Thank You ThisAMJ, I didnt notice that i moved my portal to game to my drive, "D:\SteamLibrary\steamapps\common\Portal 2\portal2" seemed to fix it! Thanks for telling me about "Browse Local Files" or i would of never known i put it in my drive! Thanks!

**Comment by betsruner** [comment]
Issue seems resolved
