### ISSUE TITLE
I followed the install instructions fully but it just isnt appearing in my library

### ISSUE THREAD

**Issue by Toomerboomer** [p2sr/Portal2SpeedrunMod#9]

**Comment by MeanTheBean** [comment]
Make sure it is on the same drive as Portal 2, if that does not work, jump out the ground floor window (as stated in the ReadMe file)

**Comment by MrHousehao** [comment]
I have also encountered this problem before. In my case, the steam store is installed on the D: \ disk, the game library is installed on the G: \ disk, and I put the mod on the G disk. This mod does not appear. Later, I found sourcemods in the directory where the D disk of the steam store was installed and put the mod in it. After restarting steam, the mod came out.
